### ISSUE TITLE
Restarting services ?

### ISSUE THREAD

**Issue by sullfu** [NuLink-network/nulink-core#4]
**Describe the Bug**
TypeError: argument of type 'NoneType' is not iterable

**To Reproduce**
nulink ursula run --config-file /home/ubuntu/nulink-1/ursula.json --rest-port 9151 --no-block-until-ready

**Traceback or Screenshots (Optional)**
OperatorBondedTracker: ✓ Operator 0xE9Dbe1B2D0207FB542C76a10c9686A67fb619F4c is bonded to staking provider 0xE9Dbe1B2D0207FB542C76a10c9686A67fb61
9F4c 
_start_ursula 
Restarting services 
x [Operator 0xE9Dbe1B2D0207FB542C76a10c9686A67fb619F4c is no longer bonded to any staking provider] - Commencing auto-shutdown sequence... 
OperatorNoLongerBonded 
finally _shutdown_ursula 
OperatorBondedTracker run exception: Traceback (most recent call last): 
File "/home/ubuntu/.local/lib/python3.8/site-packages/nulink/network/trackers.py", line 74, in run 
self._start_ursula(start_service=False) 
File "/home/ubuntu/.local/lib/python3.8/site-packages/nulink/network/trackers.py", line 104, in _start_ursula 
restart_run_arg_add('--start-service', str(start_service)) 
File "/home/ubuntu/.local/lib/python3.8/site-packages/nulink/network/trackers.py", line 92, in restart_run_arg_add 
if option_str in self._restart_run_args and (origin_option_index := self._restart_run_args.index(option_str)) >= 0: 
TypeError: argument of type 'NoneType' is not iterable

**System (please complete the following information):**
 - OS Version: Ubuntu 20.04.3 LTS
 - NULINK Version: 0.1.0
 - Ethereum Node Version:

**Comment by anyfire12** [comment]
ok, it's bug, thanks for you issue.
